### PR TITLE
Bump ADO workflow databricks cli version to 0.100.2

### PR DESCRIPTION
**Pull request by mingyu89**

### CODE REVIEW

**Review by arpitjasa-db — APPROVED** [review]
Looks great thanks @mingyu89! Can we confirm there's no more spots to bump the number though? I remember on a previous PR there were quite a few spots

**Comment by mingyu89** [comment]
@arpitjasa-db The corresponding PR for github is https://github.com/databricks/setup-cli/commit/026e5caebee871f94b68296ecd89cdd36f19a294
I searched term "0.100." in the repo. It should be all of them unless the existing version is wrong.

**Comment by mingyu89** [comment]
I don't have a way to test the change and want to wait for the approval from @niall-turbitt.

**Review by vladimirk-db — APPROVED** [review]

**Comment by mingyu89** [comment]
Tested by opening link `https://databricks-bricks.s3.amazonaws.com/v0.100.2/databricks_cli_0.100.2_darwin_arm64.zip`

**Pull request merged**
