### PR TITLE
Pinning mlflow to not pick the latest mlflow2.0 release

### PR DESCRIPTION
**Pull request by sunishsheth2009**
Signed-off-by: Sunish Sheth <sunishsheth2009@gmail.com>

### CODE REVIEW

**Review by vladimirk-db — APPROVED** [review]

**Comment by smurching** [comment]
@sunishsheth2009 thanks for the PR, looks good! Do we plan to update the example ML code in the stacks to use MLflow 2.0 once it's out?

**Comment by mengxr** [comment]
@sunishsheth2009 https://github.com/databricks/mlops-stack/blob/main/dev-requirements.txt#L4

**Comment by sunishsheth2009** [comment]
@mengxr Yes I thought about changing that: https://github.com/databricks/mlops-stack/blob/main/dev-requirements.txt#L4
but then realized that the code linked is not part of MLP. so it could download another version of MLFlow independent of the pipeline. So didn't change that. Let me know if I am missing something. 
cc @vladimirk-db and @smurching

**Comment by sunishsheth2009** [comment]
> @sunishsheth2009 thanks for the PR, looks good! Do we plan to update the example ML code in the stacks to use MLflow 2.0 once it's out?

Yes we have a follow up task to update that repo with the new 2.0 changes. :)

**Pull request merged**
